clc;clear all;close all;
%% ------------------------------------------------------------------------
%imds = imageDatastore('D:\RSI\Patch\NWPU-RESISC45','IncludeSubfolders',true,'LabelSource','foldernames');
%[imdsTest, Data] = splitEachLabel(imds,1,'randomized');
%[imdsTrain, imdsValidation] = splitEachLabel(Data,0.8,'randomized');
%imdsTrain = shuffle(imdsTrain);
%imdsValidation = shuffle(imdsValidation);
% save('imdsTrain.mat','imdsTrain');
% save('imdsValidation.mat','imdsValidation');
load('Data\imdsTrain.mat');
load('Data\imdsValidation.mat');
%% ------------------------------------------------------------------------
net = mobilenetv2;
%% ------------------------------------------------------------------------
inputSize = net.Layers(1).InputSize;
if isa(net,'SeriesNetwork')
    lgraph = layerGraph(net.Layers);
else
    lgraph = layerGraph(net);
end
%% ------------------------------------------------------------------------
[learnableLayer,classLayer] = findLayersToReplace(lgraph);
numClasses = numel(categories(imdsTrain.Labels));
if isa(learnableLayer,'nnet.cnn.layer.FullyConnectedLayer')
    newLearnableLayer = fullyConnectedLayer(numClasses, ...
        'Name','new_fc', ...
        'WeightLearnRateFactor',10, ...
        'BiasLearnRateFactor',10);
elseif isa(learnableLayer,'nnet.cnn.layer.Convolution2DLayer')
    newLearnableLayer = convolution2dLayer(1,numClasses, ...
        'Name','new_conv', ...
        'WeightLearnRateFactor',10, ...
        'BiasLearnRateFactor',10);
end
lgraph = replaceLayer(lgraph,learnableLayer.Name,newLearnableLayer);
%% --------------------------------------------------------------------
newClassLayer = classificationLayer('Name','new_classoutput');
lgraph = replaceLayer(lgraph,classLayer.Name,newClassLayer);
%% -------------------------------------------------------------------
scaleRange = [0.5 1.5];
imageAugmenter = imageDataAugmenter( ...
    'RandRotation',[-180 180],...
    'RandXReflection',true, ...  
    'RandyReflection',true, ...  
    'RandXScale',scaleRange, ...
    'RandYScale',scaleRange);
%% --------------------------------------------------------------------
augimdsTrain = augmentedImageDatastore(inputSize(1:2), imdsTrain, 'DataAugmentation', imageAugmenter);
augimdsValidation = augmentedImageDatastore(inputSize(1:2), imdsValidation);
%% --------------------------------------------------------------------
miniBatchSize = 16;
valFrequency = 350;
options = trainingOptions('sgdm', ...
    'MiniBatchSize',miniBatchSize, ...
    'MaxEpochs', 50, ...
    'InitialLearnRate', 0.001, ...
    'LearnRateSchedule', 'piecewise', ...
    'LearnRateDropPeriod', 10, ...
    'L2Regularization', 0.0001,...
    'LearnRateDropFactor', 0.9, ...
    'CheckpointPath', 'D:\temp',...
    'Shuffle', 'every-epoch', ...
    'ValidationData', augimdsValidation, ...
    'ValidationFrequency', valFrequency, ...
    'ValidationPatience', 10, ...
    'Verbose', true, ...
    'DispatchInBackground', true, ...
    'Plots', 'training-progress');
%% ------------------------------------------------------------------------
[net, info] = trainNetwork(augimdsTrain, lgraph, options);
save('TransLearnMobilenet.mat', 'net');
save('TransLearnMobileinfo.mat', 'info');
[YPred, ~] = classify(net, augimdsValidation);        
accuracy = mean(YPred == imdsValidation.Labels);
%% ------------------------------------------------------------------------
figure;
plotconfusion(imdsValidation.Labels, YPred);
grid on;
set(gca, 'FontSize', 12, 'FontWeight','bold','color',[0.95 0.95 0.95]);
figure;
cm = confusionchart(imdsValidation.Labels, YPred);
cm.ColumnSummary = 'column-normalized';
cm.RowSummary = 'row-normalized';
cm.Title = 'CIFAR-10 Confusion Matrix';
set(gca, 'FontSize', 12);